/* pethud viewer — vanilla JS, no libraries.
   Renders per-analyte trends from window.PETHUD_DATA (generated by the Ruby
   exporter) and, when served by `bin/pethud serve`, imports dropped PDFs. */
(function () {
  "use strict";

  var DATA = window.PETHUD_DATA || { patients: [], reports: [], analytes: [], series: {} };

  var SECTION_ORDER = ["Hematology", "Chemistry", "Urinalysis", "Urine Chemistry",
    "Endocrinology", "Serology", "Immunology", "Parasitology", "Microbiology",
    "Cytology", "Coagulation", "Infectious Disease"];

  var SECTION_COLOR = {
    Hematology: "#e06c9f", Chemistry: "#4aa8ff", Urinalysis: "#d29922",
    "Urine Chemistry": "#caa14a", Endocrinology: "#a371f7", Serology: "#3fb950",
    Immunology: "#56c8b0", Parasitology: "#db8b4f", Microbiology: "#8b949e",
    Cytology: "#bc8cff", Coagulation: "#f0883e", "Infectious Disease": "#6e7681"
  };

  var state = {
    patientId: null,
    view: "trends",
    search: "",
    hiddenSections: {},
    abnormalOnly: false
  };

  var $ = function (sel) { return document.querySelector(sel); };
  var el = function (tag, cls, html) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (html != null) n.innerHTML = html;
    return n;
  };

  // ---- formatting helpers -------------------------------------------------

  function fmtNum(v) {
    if (v == null) return "—";
    var s = (Math.round(v * 1000) / 1000).toString();
    return s;
  }
  function fmtDate(iso) {
    if (!iso) return "?";
    var p = iso.split("-");
    var mon = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    return mon[+p[1] - 1] + " " + (+p[2]) + " '" + p[0].slice(2);
  }
  function fmtDateShort(iso) {
    var p = iso.split("-");
    return p[1] + "/" + p[2] + "/" + p[0].slice(2);
  }
  function ms(iso) { return Date.parse(iso + "T00:00:00Z"); }

  function flagOf(point) {
    if (point.flag === "H" || point.flag === "L") return point.flag;
    if (point.value != null) {
      if (point.ref_low != null && point.value < point.ref_low) return "L";
      if (point.ref_high != null && point.value > point.ref_high) return "H";
    }
    return "ok";
  }

  // One numeric point per date (collapse reprints of the same order); keep the
  // point from the most recently imported report when a date repeats.
  function numericSeries(points) {
    var byDate = {};
    points.forEach(function (p) {
      if (p.value == null) return;
      var cur = byDate[p.date];
      if (!cur || p.report_id > cur.report_id) byDate[p.date] = p;
    });
    return Object.keys(byDate).sort().map(function (d) { return byDate[d]; });
  }

  function qualSeries(points) {
    // Keep one per date, prefer non-empty textual result.
    var byDate = {};
    points.forEach(function (p) {
      var txt = (p.result_text || "").trim();
      if (!txt) return;
      var cur = byDate[p.date];
      if (!cur || p.report_id > cur.report_id) byDate[p.date] = p;
    });
    return Object.keys(byDate).sort().map(function (d) { return byDate[d]; });
  }

  // ---- scales -------------------------------------------------------------

  function scales(pts, box, refLow, refHigh) {
    var xs = pts.map(function (p) { return ms(p.date); });
    var vs = pts.map(function (p) { return p.value; });
    if (refLow != null) vs.push(refLow);
    if (refHigh != null) vs.push(refHigh);
    var xmin = Math.min.apply(null, xs), xmax = Math.max.apply(null, xs);
    var vmin = Math.min.apply(null, vs), vmax = Math.max.apply(null, vs);
    if (xmin === xmax) { xmin -= 1; xmax += 1; }
    var span = (vmax - vmin) || Math.abs(vmax) || 1;
    vmin -= span * 0.12; vmax += span * 0.12;
    var X = function (t) { return box.l + (box.w) * (t - xmin) / (xmax - xmin); };
    var Y = function (v) { return box.t + box.h - (box.h) * (v - vmin) / (vmax - vmin); };
    return { X: X, Y: Y, xmin: xmin, xmax: xmax, vmin: vmin, vmax: vmax };
  }

  function svgEl(w, h, cls) {
    return '<svg class="' + cls + '" viewBox="0 0 ' + w + ' ' + h +
      '" preserveAspectRatio="none" xmlns="http://www.w3.org/2000/svg">';
  }

  // Latest reference range across the series (band shading uses this).
  function latestRef(pts) {
    for (var i = pts.length - 1; i >= 0; i--) {
      if (pts[i].ref_low != null || pts[i].ref_high != null) {
        return { low: pts[i].ref_low, high: pts[i].ref_high };
      }
    }
    return { low: null, high: null };
  }

  // ---- sparkline ----------------------------------------------------------

  function sparkline(pts) {
    var W = 208, H = 46;
    if (pts.length === 0) return svgEl(W, H, "spark") + "</svg>";
    var ref = latestRef(pts);
    var box = { l: 2, t: 4, w: W - 4, h: H - 8 };
    var s = scales(pts, box, ref.low, ref.high);
    var out = svgEl(W, H, "spark");

    if (ref.low != null && ref.high != null) {
      var yTop = s.Y(ref.high), yBot = s.Y(ref.low);
      out += '<rect class="ref-band" x="' + box.l + '" y="' + yTop.toFixed(1) +
        '" width="' + box.w + '" height="' + Math.max(0, yBot - yTop).toFixed(1) + '"/>';
    }
    if (pts.length > 1) {
      var d = pts.map(function (p, i) {
        return (i ? "L" : "M") + s.X(ms(p.date)).toFixed(1) + " " + s.Y(p.value).toFixed(1);
      }).join(" ");
      out += '<path class="series-line" d="' + d + '"/>';
    }
    pts.forEach(function (p, i) {
      var r = i === pts.length - 1 ? 3 : 2;
      out += '<circle class="pt ' + flagOf(p) + '" cx="' + s.X(ms(p.date)).toFixed(1) +
        '" cy="' + s.Y(p.value).toFixed(1) + '" r="' + r + '"/>';
    });
    return out + "</svg>";
  }

  // ---- big detail chart with axes + hover --------------------------------

  function bigChart(pts) {
    var W = 820, H = 280;
    var box = { l: 52, t: 16, w: W - 70, h: H - 52 };
    var ref = latestRef(pts);
    var s = scales(pts, box, ref.low, ref.high);
    var out = svgEl(W, H, "bigchart");

    // y gridlines + labels
    var ticks = niceTicks(s.vmin, s.vmax, 5);
    ticks.forEach(function (tv) {
      var y = s.Y(tv).toFixed(1);
      out += '<line class="grid-line" x1="' + box.l + '" y1="' + y + '" x2="' + (box.l + box.w) + '" y2="' + y + '"/>';
      out += '<text class="axis-label" x="' + (box.l - 6) + '" y="' + (+y + 3) + '" text-anchor="end">' + fmtNum(tv) + "</text>";
    });

    // reference band
    if (ref.low != null && ref.high != null) {
      var yTop = s.Y(ref.high), yBot = s.Y(ref.low);
      out += '<rect class="ref-band" x="' + box.l + '" y="' + yTop.toFixed(1) + '" width="' + box.w + '" height="' + Math.max(0, yBot - yTop).toFixed(1) + '"/>';
      out += '<line class="ref-edge" x1="' + box.l + '" y1="' + yTop.toFixed(1) + '" x2="' + (box.l + box.w) + '" y2="' + yTop.toFixed(1) + '"/>';
      out += '<line class="ref-edge" x1="' + box.l + '" y1="' + yBot.toFixed(1) + '" x2="' + (box.l + box.w) + '" y2="' + yBot.toFixed(1) + '"/>';
    }

    // x labels — thinned so clustered dates don't overlap. Anchor on the most
    // recent point (walk right-to-left) so the latest date always reads clean.
    var label = {}, prevX = 1e9;
    for (var k = pts.length - 1; k >= 0; k--) {
      var lx = s.X(ms(pts[k].date));
      if (prevX - lx >= 60 || k === pts.length - 1) { label[k] = true; prevX = lx; }
    }
    pts.forEach(function (p, i) {
      if (!label[i]) return;
      var anchor = i === 0 ? "start" : i === pts.length - 1 ? "end" : "middle";
      out += '<text class="axis-label" x="' + s.X(ms(p.date)).toFixed(1) + '" y="' + (box.t + box.h + 16) +
        '" text-anchor="' + anchor + '">' + fmtDateShort(p.date) + "</text>";
    });

    if (pts.length > 1) {
      var d = pts.map(function (p, i) {
        return (i ? "L" : "M") + s.X(ms(p.date)).toFixed(1) + " " + s.Y(p.value).toFixed(1);
      }).join(" ");
      out += '<path class="series-line" d="' + d + '"/>';
    }
    pts.forEach(function (p) {
      out += '<circle class="pt ' + flagOf(p) + '" data-date="' + p.date + '" data-v="' + p.value +
        '" cx="' + s.X(ms(p.date)).toFixed(1) + '" cy="' + s.Y(p.value).toFixed(1) + '" r="3.5"/>';
    });
    return out + "</svg>";
  }

  function niceTicks(min, max, count) {
    var span = max - min;
    if (span <= 0) return [min];
    var step = Math.pow(10, Math.floor(Math.log10(span / count)));
    var err = (count * step) / span;
    if (err <= 0.15) step *= 10; else if (err <= 0.35) step *= 5; else if (err <= 0.75) step *= 2;
    var ticks = [];
    var start = Math.ceil(min / step) * step;
    for (var v = start; v <= max + step * 0.5; v += step) ticks.push(Math.round(v / step) * step);
    return ticks;
  }

  // ---- data access --------------------------------------------------------

  function currentPatient() {
    return DATA.patients.find(function (p) { return p.id === state.patientId; }) || DATA.patients[0];
  }
  function seriesFor(analyteId) {
    var byPatient = DATA.series[String(state.patientId)] || {};
    return byPatient[String(analyteId)] || [];
  }
  function patientAnalytes() {
    return DATA.analytes.filter(function (a) { return a.patient_ids.indexOf(state.patientId) >= 0; });
  }

  // ---- trends view --------------------------------------------------------

  function renderTrends() {
    var host = $("#trends");
    host.innerHTML = "";
    var analytes = patientAnalytes();
    var q = state.search.toLowerCase();

    var bySection = {};
    analytes.forEach(function (a) {
      if (state.hiddenSections[a.section]) return;
      if (q && a.name.toLowerCase().indexOf(q) < 0) return;
      var pts = seriesFor(a.id);
      var num = numericSeries(pts);
      var hasFlag = num.some(function (p) { return flagOf(p) !== "ok"; });
      if (state.abnormalOnly && !hasFlag) return;
      (bySection[a.section] || (bySection[a.section] = [])).push({ a: a, pts: pts, num: num });
    });

    var sections = Object.keys(bySection).sort(function (x, y) {
      return SECTION_ORDER.indexOf(x) - SECTION_ORDER.indexOf(y);
    });

    if (sections.length === 0) {
      host.appendChild(el("div", "empty", "No analytes match the current filters."));
      return;
    }

    sections.forEach(function (sec) {
      var color = SECTION_COLOR[sec] || "#8b949e";
      var block = el("div", "section-block");
      var head = el("div", "section-head");
      head.innerHTML = '<span class="bar" style="background:' + color + '"></span>' +
        "<h2>" + sec + '</h2><span class="n">' + bySection[sec].length + "</span>";
      block.appendChild(head);
      var grid = el("div", "grid");
      bySection[sec].forEach(function (item) { grid.appendChild(card(item)); });
      block.appendChild(grid);
      host.appendChild(block);
    });
  }

  function card(item) {
    var a = item.a, num = item.num;
    var c = el("div", "card");
    c.setAttribute("data-analyte", a.id);

    if (a.numeric && num.length) {
      var last = num[num.length - 1];
      var fl = flagOf(last);
      c.classList.add("flag-" + (fl === "ok" ? "ok" : fl));
      var prev = num.length > 1 ? num[num.length - 2] : null;
      var deltaHtml = "";
      if (prev) {
        var dv = last.value - prev.value;
        var dir = dv > 0 ? "up" : dv < 0 ? "down" : "flat";
        var arrow = dv > 0 ? "▲" : dv < 0 ? "▼" : "▬";
        deltaHtml = '<span class="delta ' + dir + '">' + arrow + " " + fmtNum(Math.abs(dv)) + "</span>";
      }
      var ref = latestRef(num);
      var refTxt = (ref.low != null && ref.high != null) ? (fmtNum(ref.low) + "–" + fmtNum(ref.high)) : "—";
      c.innerHTML =
        '<div class="card-top"><span class="card-name">' + a.name + '</span>' +
        '<span class="card-unit">' + (a.unit || "") + "</span></div>" +
        '<div class="card-value"><span class="v ' + fl + '">' + fmtNum(last.value) + "</span>" + deltaHtml + "</div>" +
        sparkline(num) +
        '<div class="card-foot"><span>' + refTxt + '</span><span>' + num.length + " pts · " + fmtDate(last.date) + "</span></div>";
    } else {
      // qualitative timeline
      var qs = qualSeries(item.pts);
      var lastq = qs.length ? qs[qs.length - 1] : null;
      var badges = qs.slice(-6).map(function (p) {
        return '<span class="b" title="' + fmtDate(p.date) + '">' + escapeHtml(p.result_text) + "</span>";
      }).join("");
      c.classList.add("flag-ok");
      c.innerHTML =
        '<div class="card-top"><span class="card-name">' + a.name + "</span></div>" +
        '<div class="card-value"><span class="v ok" style="font-size:14px">' +
          (lastq ? escapeHtml(lastq.result_text) : "—") + "</span></div>" +
        '<div class="qual-badges">' + badges + "</div>" +
        '<div class="card-foot"><span>qualitative</span><span>' + qs.length + " obs</span></div>";
    }

    c.addEventListener("click", function () { openDetail(a.id); });
    return c;
  }

  function escapeHtml(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (ch) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[ch];
    });
  }

  // ---- detail overlay -----------------------------------------------------

  function openDetail(analyteId) {
    var a = DATA.analytes.find(function (x) { return x.id === analyteId; });
    var pts = seriesFor(analyteId);
    var body = $("#detail-body");
    var color = SECTION_COLOR[a.section] || "#8b949e";

    var head = '<div class="detail-head"><span class="bar" style="display:inline-block;width:4px;height:18px;background:' +
      color + ';border-radius:2px"></span><h2>' + a.name + '</h2><span class="sec">' + a.section +
      (a.unit ? " · " + a.unit : "") + "</span></div>";

    var num = numericSeries(pts);
    var chartHtml, sub;
    if (a.numeric && num.length) {
      var ref = latestRef(num);
      var vals = num.map(function (p) { return p.value; });
      sub = '<div class="detail-sub">' + num.length + " points · range " +
        fmtNum(Math.min.apply(null, vals)) + "–" + fmtNum(Math.max.apply(null, vals)) +
        (ref.low != null ? " · reference " + fmtNum(ref.low) + "–" + fmtNum(ref.high) : "") + "</div>";
      chartHtml = bigChart(num);
    } else {
      sub = '<div class="detail-sub">qualitative observations</div>';
      chartHtml = "";
    }

    body.innerHTML = head + sub + chartHtml + detailTable(pts, a);
    $("#detail").hidden = false;

    if (a.numeric && num.length) attachHover(body.querySelector("svg.bigchart"), num, a);
  }

  function detailTable(pts, a) {
    var rows = pts.slice().sort(function (x, y) {
      return y.date.localeCompare(x.date) || y.report_id - x.report_id;
    });
    var seen = {};
    var html = '<table class="detail-table"><thead><tr><th>Date</th><th>Result</th><th>Reference</th><th>Flag</th></tr></thead><tbody>';
    rows.forEach(function (p) {
      if (seen[p.date]) return; // one row per date
      seen[p.date] = true;
      var fl = flagOf(p);
      var ref = (p.ref_low != null && p.ref_high != null) ? fmtNum(p.ref_low) + "–" + fmtNum(p.ref_high) : (p.ref_low != null || p.ref_high != null ? "" : "");
      var val = p.value != null ? (p.qualifier ? p.qualifier + " " : "") + fmtNum(p.value) : escapeHtml(p.result_text);
      var flBadge = fl === "ok" ? "" : '<span class="pill ' + fl + '">' + fl + "</span>";
      html += '<tr class="' + fl + '"><td class="dt">' + fmtDate(p.date) + '</td><td class="value">' + val +
        (p.unit ? " " + p.unit : "") + '</td><td>' + ref + "</td><td>" + flBadge + "</td></tr>";
    });
    return html + "</tbody></table>";
  }

  // Hover crosshair + tooltip on the detail chart.
  function attachHover(svg, num, a) {
    if (!svg) return;
    var tip = el("div", "tooltip");
    tip.style.display = "none";
    document.body.appendChild(tip);
    var circles = Array.prototype.slice.call(svg.querySelectorAll("circle.pt"));

    function move(ev) {
      var rect = svg.getBoundingClientRect();
      var sx = (ev.clientX - rect.left) / rect.width * 820; // viewBox space
      var best = null, bd = Infinity;
      circles.forEach(function (c) {
        var cx = +c.getAttribute("cx");
        var d = Math.abs(cx - sx);
        if (d < bd) { bd = d; best = c; }
      });
      if (!best) return;
      circles.forEach(function (c) { c.setAttribute("r", c === best ? 5 : 3.5); });
      var date = best.getAttribute("data-date");
      var p = num.find(function (q) { return q.date === date; });
      tip.innerHTML = fmtDate(date) + " &nbsp; <b>" + fmtNum(p.value) + (a.unit ? " " + a.unit : "") + "</b>" +
        (flagOf(p) !== "ok" ? ' <span style="color:var(--' + (flagOf(p) === "H" ? "high" : "low") + ')">' + flagOf(p) + "</span>" : "");
      tip.style.display = "block";
      tip.style.left = (ev.clientX + 12) + "px";
      tip.style.top = (ev.clientY - 10) + "px";
    }
    svg.addEventListener("mousemove", move);
    svg.addEventListener("mouseleave", function () {
      tip.style.display = "none";
      circles.forEach(function (c) { c.setAttribute("r", 3.5); });
    });
    // clean up tooltip when overlay closes
    $("#detail").addEventListener("close-detail", function () { tip.remove(); }, { once: true });
  }

  function closeDetail() {
    var d = $("#detail");
    d.dispatchEvent(new Event("close-detail"));
    d.hidden = true;
    $("#detail-body").innerHTML = "";
  }

  // ---- reports view -------------------------------------------------------

  function renderReports() {
    var host = $("#reports");
    host.innerHTML = "";
    var reports = DATA.reports.filter(function (r) { return r.patient_id === state.patientId; })
      .sort(function (a, b) { return b.date.localeCompare(a.date); });
    if (!reports.length) { host.appendChild(el("div", "empty", "No reports.")); return; }

    var grid = el("div", "report-grid");
    reports.forEach(function (r) { grid.appendChild(reportCard(r)); });
    host.appendChild(grid);
  }

  function reportCard(r) {
    // collect flagged measurements for this report from the series
    var flagged = [];
    var smap = DATA.series[String(state.patientId)] || {};
    DATA.analytes.forEach(function (a) {
      (smap[String(a.id)] || []).forEach(function (p) {
        if (p.report_id !== r.id) return;
        var fl = flagOf(p);
        if (fl !== "ok") flagged.push({ a: a, p: p, fl: fl });
      });
    });
    flagged.sort(function (x, y) {
      return SECTION_ORDER.indexOf(x.a.section) - SECTION_ORDER.indexOf(y.a.section) || x.a.name.localeCompare(y.a.name);
    });

    var c = el("div", "report-card");
    var rows = flagged.map(function (f) {
      var ref = (f.p.ref_low != null) ? fmtNum(f.p.ref_low) + "–" + fmtNum(f.p.ref_high) : "";
      return '<tr class="' + f.fl + '"><td class="name">' + f.a.name + '</td><td class="val">' +
        fmtNum(f.p.value) + '</td><td class="ref">' + ref + '</td><td><span class="pill ' + f.fl + '">' + f.fl + "</span></td></tr>";
    }).join("");

    c.innerHTML =
      "<h3>" + fmtDate(r.date) + "</h3>" +
      '<div class="rmeta"><span class="k">clinic</span> ' + escapeHtml(r.clinic_name || "—") +
      ' · <span class="k">age</span> ' + escapeHtml(r.age_text || "—") +
      (r.lab_id ? ' · <span class="k">lab</span> ' + r.lab_id : "") + "</div>" +
      (r.idexx_services ? '<div class="svc">' + escapeHtml(r.idexx_services) + "</div>" : "") +
      (flagged.length
        ? '<div class="section-tag">' + flagged.length + ' out of range</div><table class="flag-table"><tbody>' + rows + "</tbody></table>"
        : '<div class="section-tag" style="color:var(--normal)">all values within range</div>');
    return c;
  }

  // ---- sidebar / chrome ---------------------------------------------------

  function renderSidebar() {
    var ul = $("#section-filter");
    ul.innerHTML = "";
    var counts = {};
    patientAnalytes().forEach(function (a) { counts[a.section] = (counts[a.section] || 0) + 1; });
    Object.keys(counts).sort(function (x, y) {
      return SECTION_ORDER.indexOf(x) - SECTION_ORDER.indexOf(y);
    }).forEach(function (sec) {
      var li = el("li", state.hiddenSections[sec] ? "off" : "on");
      var color = SECTION_COLOR[sec] || "#8b949e";
      li.innerHTML = '<span class="label"><span class="dot" style="background:' + color + '"></span>' + sec +
        '</span><span class="count">' + counts[sec] + "</span>";
      li.addEventListener("click", function () {
        state.hiddenSections[sec] = !state.hiddenSections[sec];
        renderSidebar(); renderTrends();
      });
      ul.appendChild(li);
    });

    var p = currentPatient();
    $("#corpus-meta").innerHTML = "Generated<br>" + (DATA.generated_at ? DATA.generated_at.replace("T", " ").slice(0, 16) + " UTC" : "—") +
      "<br><br>" + DATA.reports.length + " reports · " + DATA.analytes.length + " analytes";
    var ids = (p.identities || []).map(function (i) { return escapeHtml(i.pet_name + " / " + i.owner); });
    $("#patient-meta").innerHTML = p.report_count + " reports · " +
      fmtDate(p.date_range[0]) + " → " + fmtDate(p.date_range[1]) +
      (ids.length > 1 ? "<br>aliases: " + Array.from(new Set(ids)).join(", ") : "");
  }

  function renderPatientSelect() {
    var sel = $("#patient");
    sel.innerHTML = "";
    DATA.patients.forEach(function (p) {
      var o = el("option");
      o.value = p.id;
      o.textContent = p.name + " (" + p.species + ", " + p.report_count + ")";
      sel.appendChild(o);
    });
    sel.value = state.patientId;
  }

  function renderAll() {
    renderPatientSelect();
    renderSidebar();
    if (state.view === "trends") { $("#trends").hidden = false; $("#reports").hidden = true; renderTrends(); }
    else { $("#trends").hidden = true; $("#reports").hidden = false; renderReports(); }
  }

  // ---- events -------------------------------------------------------------

  function wire() {
    $("#patient").addEventListener("change", function (e) {
      state.patientId = +e.target.value; renderAll();
    });
    $("#view-toggle").addEventListener("click", function (e) {
      if (e.target.tagName !== "BUTTON") return;
      state.view = e.target.getAttribute("data-view");
      Array.prototype.forEach.call(this.children, function (b) { b.classList.toggle("active", b === e.target); });
      renderAll();
    });
    var searchTimer;
    $("#search").addEventListener("input", function (e) {
      clearTimeout(searchTimer);
      var v = e.target.value;
      searchTimer = setTimeout(function () { state.search = v; renderTrends(); }, 120);
    });
    $("#abnormal-only").addEventListener("change", function (e) {
      state.abnormalOnly = e.target.checked; renderTrends();
    });
    $("#detail-close").addEventListener("click", closeDetail);
    $("#detail").addEventListener("click", function (e) { if (e.target === this) closeDetail(); });
    document.addEventListener("keydown", function (e) { if (e.key === "Escape") closeDetail(); });

    setupDropzone();
  }

  // ---- drag & drop import -------------------------------------------------

  function setupDropzone() {
    var zone = $("#dropzone");
    var depth = 0;
    window.addEventListener("dragenter", function (e) {
      if (!hasFiles(e)) return;
      e.preventDefault(); depth++; zone.hidden = false;
    });
    window.addEventListener("dragover", function (e) { if (hasFiles(e)) e.preventDefault(); });
    window.addEventListener("dragleave", function (e) {
      depth--; if (depth <= 0) { depth = 0; zone.hidden = true; }
    });
    window.addEventListener("drop", function (e) {
      e.preventDefault(); depth = 0; zone.hidden = true;
      var files = Array.prototype.slice.call(e.dataTransfer.files).filter(function (f) {
        return f.name.toLowerCase().endsWith(".pdf");
      });
      if (files.length) importFiles(files);
    });
  }
  function hasFiles(e) {
    return e.dataTransfer && Array.prototype.indexOf.call(e.dataTransfer.types || [], "Files") >= 0;
  }

  function importFiles(files) {
    if (location.protocol === "file:") {
      toast("Drag-and-drop import needs the local server. Run: bin/pethud serve", "err", 6000);
      return;
    }
    var i = 0, imported = 0;
    function next() {
      if (i >= files.length) {
        toast(imported + " report(s) imported.", "ok", 3500);
        return;
      }
      var f = files[i++];
      toast("Importing " + f.name + "…", null, 60000);
      f.arrayBuffer().then(function (buf) {
        return fetch("/api/import", {
          method: "POST",
          headers: { "X-Filename": f.name, "Content-Type": "application/pdf" },
          body: buf
        });
      }).then(function (r) { return r.json(); }).then(function (res) {
        if (res.ok) {
          imported++;
          DATA = res.data; window.PETHUD_DATA = DATA;
          ensurePatient();
          renderAll();
          next();
        } else {
          toast("Failed: " + (res.error || f.name), "err", 5000); next();
        }
      }).catch(function (err) {
        toast("Import error: " + err.message, "err", 5000); next();
      });
    }
    next();
  }

  var toastTimer;
  function toast(msg, kind, ttl) {
    var t = $("#toast");
    t.textContent = msg;
    t.className = "toast" + (kind ? " " + kind : "");
    t.hidden = false;
    clearTimeout(toastTimer);
    if (ttl) toastTimer = setTimeout(function () { t.hidden = true; }, ttl);
  }

  function ensurePatient() {
    if (!DATA.patients.length) { state.patientId = null; return; }
    if (!DATA.patients.some(function (p) { return p.id === state.patientId; })) {
      state.patientId = DATA.patients[0].id;
    }
  }

  // ---- boot ---------------------------------------------------------------

  function boot() {
    if (!DATA.patients || !DATA.patients.length) {
      $("#trends").innerHTML = '<div class="empty">No data yet. Import reports with <code>bin/pethud import samples/</code> ' +
        "or drop a PDF here while running <code>bin/pethud serve</code>.</div>";
      $("#patient-meta").textContent = "";
      return;
    }
    state.patientId = DATA.patients[0].id;
    wire();
    applyHash();
    renderAll();
    if (state.openAnalyte != null) openDetail(state.openAnalyte);
  }

  // Optional deep links: #reports, #trends, #a=<analyteId> (open a detail).
  function applyHash() {
    var h = (location.hash || "").replace(/^#/, "");
    if (!h) return;
    if (h === "reports" || h === "trends") {
      state.view = h;
      Array.prototype.forEach.call($("#view-toggle").children, function (b) {
        b.classList.toggle("active", b.getAttribute("data-view") === h);
      });
    } else if (/^a=(\d+)$/.test(h)) {
      state.openAnalyte = +RegExp.$1;
    }
  }

  document.addEventListener("DOMContentLoaded", boot);
})();
